env:
  KAIZEN_ROLE_ARN: ${BRANCH_ROLE_ARN}
  KAIZEN_DOMAIN_NAME: ${BRANCH_DOMAIN_NAME}
  KAIZEN_DISTRIBUTION_ID: ${BRANCH_DISTRIBUTION_ID}
  GITHUB_REGISTRY_TOKEN: ${GITHUB_REGISTRY_TOKEN}

x-defaults: &defaults
  agent_query_rules: ["queue=build-unrestricted"]
  plugins:
    - docker-compose#v3.9.0:
        run: build

steps:
  # - name: ":butterfly: Release"
  #   command: ".buildkite/scripts/release.sh"
  #   timeout_in_minutes: 15
  #   if: build.env("CHANGESETS_RELEASE") == "true" || (build.branch == "main" && build.author.name == "github-actions[bot]")
  #   <<: *defaults
  #   plugins:
  #     - cultureamp/aws-assume-role#v0.2.0:
  #         role: "${KAIZEN_ROLE_ARN}"
  #     - docker-compose#v3.9.0:
  #         run: release
  #   notify:
  #     - slack: "#wol_kaizen"
  #       if: build.state == "passed"
  #     - slack: "#wol_kaizen"
  #       if: build.state == "failed"

  - name: ":playwright: Running Playwright on ${KAIZEN_DOMAIN_NAME}"
    key: "playwright-step"
    command: ".buildkite/scripts/run-playwright.sh"
    timeout_in_minutes: 15
    branches: "!main !canary"
    depends_on: "publish-step"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]
    plugins:
      - docker#v3.13.0:
          image: mcr.microsoft.com/playwright:v1.35.1-focal
          propagate-environment: true
